/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login.store": [],
    "logout": [],
    "password.email": [],
    "password.update": [],
    "register.store": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "home": [],
    "followings": [],
    "posts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "posts.create": [],
    "posts.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "welcome": [],
    "login": [],
    "register": [],
    "password.reset": [],
    "language.switch": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
